name: Build on Debian

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cd tests/ci/ && docker build -t syntalos -f ./Dockerfile-debian .
      
    - name: Build & Test
      run: docker run -t -e COMPILER_VENDOR=$CVENDOR -e CC=gcc -e CXX=g++ -v `pwd`:/build syntalos
           ./tests/ci/build-and-test.sh
