name: Build on Ubuntu

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        mkdir env-prep && cd env-prep
        sudo ../tests/ci/install-deps-deb.sh

    - name: Build 3rd-party components
      run: |
        sudo apt install python3-pip
        sudo apt purge meson
        sudo pip3 install meson
        cd env-prep && sudo ../tests/ci/make-install-3rdparty.sh
        rm -rf env-prep
      
    - name: Build & Test
      run: ./tests/ci/build-and-test.sh
